FROM maven:3.9-eclipse-temurin-17 AS test
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn test -Ptest
RUN mvn clean package -DskipTests
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=test /app/target/*.jar /app/app.jar
COPY --from=test /app/target/surefire-reports /app/surefire-reports || true
COPY --from=test /app/target/site /app/site || true
RUN mkdir -p uploads
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
